import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/providers/theme-provider';

const raleway = Raleway({
  subsets: ['latin'],
  variable: '--font-raleway-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${raleway.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
